#!/usr/bin/env bats
# =============================================================================
# Scenario: post-install / warmup sequence
# ---------------------------------------------------------------------------
# Multiple scrapes during the warmup period.  The first scrape returns empty,
# the second returns data generated by the first scrape's background task, and
# the third is fully stable (stale-cache pipeline is primed).
# =============================================================================

load '../../lib/test_helper'

setup() {
    sandbox_create
    mock_reset_all
    trace_init
    mock_ps_fast_fail
    mock_set_response sleep "" 0
    mock_set_response hostname "testhost"
    NFS_SCRIPT="$(get_nfs_script)"
    ISCSI_SCRIPT="$(get_iscsi_script)"
    S3_SCRIPT="$(get_s3_script)"
}

teardown() {
    if [[ "${BATS_TEST_COMPLETED:-}" != "1" ]]; then
        echo "--- TRACE LOG ---" >&3; trace_dump 3
    fi
    sandbox_destroy
}

# --------------------------------------------------------------------------- #

@test "warmup: NFS converges from empty to correct in 2 scrapes" {
    mock_nfs_healthy

    # --- Scrape 1: no cache yet → empty body ----------------------------
    local resp1 body1
    resp1="$(http_get_metrics "$NFS_SCRIPT")"
    assert_http_200 "$resp1"
    body1="$(http_extract_body "$resp1")"
    [[ -z "$body1" ]]

    # Wait for the background collector started by scrape 1 to finish.
    _sandbox_wait_background

    # --- Scrape 2: returns cache written by scrape 1's bg ---------------
    local resp2 body2
    resp2="$(http_get_metrics "$NFS_SCRIPT")"
    assert_http_200 "$resp2"
    body2="$(http_extract_body "$resp2")"

    # Now we should see real NFS metrics with healthy value (1).
    [[ -n "$body2" ]]
    assert_metric_equals "$body2" "nexenta_nfs_mount_status" "1"

    _sandbox_wait_background

    # --- Scrape 3: stable — same value as scrape 2 ----------------------
    local resp3 body3
    resp3="$(http_get_metrics "$NFS_SCRIPT")"
    assert_http_200 "$resp3"
    body3="$(http_extract_body "$resp3")"
    assert_metric_equals "$body3" "nexenta_nfs_mount_status" "1"
}

@test "warmup: state stabilizes after 3 scrapes" {
    mock_nfs_healthy

    local bodies=()

    # Scrape 1 — empty
    local resp
    resp="$(http_get_metrics "$NFS_SCRIPT")"
    bodies+=("$(http_extract_body "$resp")")
    _sandbox_wait_background

    # Scrape 2 — data from scrape-1 bg
    resp="$(http_get_metrics "$NFS_SCRIPT")"
    bodies+=("$(http_extract_body "$resp")")
    _sandbox_wait_background

    # Scrape 3 — stable
    resp="$(http_get_metrics "$NFS_SCRIPT")"
    bodies+=("$(http_extract_body "$resp")")
    _sandbox_wait_background

    # Body 0 is empty; bodies 1 and 2 should be identical (stable).
    [[ -z "${bodies[0]}" ]]
    [[ -n "${bodies[1]}" ]]
    [[ "${bodies[1]}" == "${bodies[2]}" ]]
}

@test "warmup: trace log records all mock invocations during warmup" {
    mock_nfs_healthy

    # Run 3 warmup scrapes.
    http_get_metrics "$NFS_SCRIPT" >/dev/null
    _sandbox_wait_background

    http_get_metrics "$NFS_SCRIPT" >/dev/null
    _sandbox_wait_background

    http_get_metrics "$NFS_SCRIPT" >/dev/null
    _sandbox_wait_background

    # The trace log should record at least 3 invocations of the NFS check
    # (one per scrape's background collector).
    local count
    count="$(trace_count "nfs")"
    [[ "$count" -ge 3 ]]

    # Hostname mock should have been called as well.
    trace_has "hostname"
}
